name: Didata CI workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.1
        otp-version: 22.2
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Unit Tests
      run: mix test
    - name: Run Credo
      run: mix credo --strict
    - name: Run Format
      run: mix format --check-formatted
